In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
df = pd.read_csv('Churn_Modelling.csv')

In [3]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
# EstimatedSalary column will be independent variable

In [5]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [6]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df.shape

(10000, 11)

In [8]:
df.isnull().sum()

CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CreditScore      10000 non-null  int64
 1   Geography        10000 non-null  object
 2   Gender           10000 non-null  object
 3   Age              10000 non-null  int64
 4   Tenure           10000 non-null  int64
 5   Balance          10000 non-null  float64
 6   NumOfProducts    10000 non-null  int64
 7   HasCrCard        10000 non-null  int64
 8   IsActiveMember   10000 non-null  int64
 9   EstimatedSalary  10000 non-null  float64
 10  Exited           10000 non-null  int64
dtypes: float64(2), int64(7), object(2)
memory usage: 859.5+ KB

In [10]:
df.describe()

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,650.528800,38.921800,5.012800,76485.889288,1.530200,0.70550,0.515100,100090.239881,0.203700
std,96.653299,10.487806,2.892174,62397.405202,0.581654,0.45584,0.499797,57510.492818,0.402769
min,350.000000,18.000000,0.000000,0.000000,1.000000,0.00000,0.000000,11.580000,0.000000
25%,584.000000,32.000000,3.000000,0.000000,1.000000,0.00000,0.000000,51002.110000,0.000000
50%,652.000000,37.000000,5.000000,97198.540000,1.000000,1.00000,1.000000,100193.915000,0.000000
75%,718.000000,44.000000,7.000000,127644.240000,2.000000,1.00000,1.000000,149388.247500,0.000000
max,850.000000,92.000000,10.000000,250898.090000,4.000000,1.00000,1.000000,199992.480000,1.000000

In [11]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [12]:
# Label Encoding Gender column
label_encode_gender = LabelEncoder()
df['Gender'] = label_encode_gender.fit_transform(df['Gender'])

In [13]:
# One hot encoding Geography column
onehot_encode_geography = OneHotEncoder()

In [28]:
geo_encoded = onehot_encode_geography.fit_transform(df[['Geography']]).toarray()
# Can be done using 
## onehot_encode_geography.fit_transform(df['Geography'].values.reshape(-1, 1)).toarray()

In [30]:
# Converting to dataframe
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encode_geography.get_feature_names_out(['Geography']))

In [31]:
# combining the dataframes
df = pd.concat([df, geo_encoded_df], axis=1)

In [32]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,France,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,France,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [33]:
# Dropping Geography column
df.drop(['Geography'], axis=1, inplace=True)

In [34]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [35]:
# Splitting the data into dependent and independent variables
X = df.drop(['EstimatedSalary'], axis=1)
y = df['EstimatedSalary']

In [36]:
# Splitting the data into training and testing data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [37]:
# Scaling the data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [38]:
# Save label encoder, one hot encoder and scaler as pickle files
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encode_gender, file)

with open('onehot_encoder_geography.pkl', 'wb') as file:
    pickle.dump(onehot_encode_geography, file)

with open('scaler.pkl', 'wb') as file:
    pickle.dump(scaler, file)

### ANN Regression

In [39]:
import tensorflow as tf
from tensorflow.keras.models import Sequential # type: ignore
from tensorflow.keras.layers import Dense # type: ignore

In [40]:
# Building the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)), # hidden layer 1
    Dense(32, activation='relu'), # hidden layer 2
    Dense(1) # output layer for regression
]
)

c:\Anush\Anush_Documents\Machine_learning\Deep_Learning\ANN\Regression\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [41]:
# Compiling the model
model.compile(optimizer='adam', loss='mean_absolute_error', metrics=['mae'])

In [42]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [44]:
# Set up the log directory for tensorboard
import datetime
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [45]:
# Set up the tensorboard callback
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

In [46]:
# Setups the early stopping callback
early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [47]:
# Training the model
history = model.fit(X_train, y_train, 
          validation_data=(X_test, y_test), 
          epochs=100, callbacks=[early_stopping, tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 100740.2344 - mae: 100740.2344 - val_loss: 98519.5469 - val_mae: 98519.5469
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 99332.7891 - mae: 99332.7891 - val_loss: 96931.2031 - val_mae: 96931.2031
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 98108.6875 - mae: 98108.6875 - val_loss: 92829.4609 - val_mae: 92829.4609
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 92000.5938 - mae: 92000.5938 - val_loss: 86006.5391 - val_mae: 86006.5391
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 85115.4922 - mae: 85115.4922 - val_loss: 77175.4219 - val_mae: 77175.4219
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 76653.3750 - mae: 76653.3750 - val_loss: 68142.9219 - val_mae: 68142.9219
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 67078.6406 - mae: 67078.6406 - val_loss: 60385.4922 - val_mae: 60385.4922
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 59921.8008 - mae: 59921.8008 - val_loss: 55021.4844 - val_mae: 55021.4844
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 53904.6719 - mae: 53904.6719 - val_loss: 52161.7422 - val_mae: 52161.7422
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 52436.2461 - mae: 52436.2461 - val_loss: 51070.9219 - val_mae: 51070.9219
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 50896.6875 - mae: 50896.6875 - val_loss: 50749.2461 - val_mae: 50749.2461
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49807.8008 - mae: 49807.8008 - val_loss: 50658.5312 - val_mae: 50658.5312
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49938.4492 - mae: 49938.4492 - val_loss: 50607.9062 - val_mae: 50607.9062
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50147.9141 - mae: 50147.9141 - val_loss: 50570.0469 - val_mae: 50570.0469
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49990.5742 - mae: 49990.5742 - val_loss: 50543.0508 - val_mae: 50543.0508
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49964.4844 - mae: 49964.4844 - val_loss: 50515.7109 - val_mae: 50515.7109
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49427.2812 - mae: 49427.2812 - val_loss: 50495.0547 - val_mae: 50495.0547
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50327.9023 - mae: 50327.9023 - val_loss: 50484.2852 - val_mae: 50484.2852
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49683.9648 - mae: 49683.9648 - val_loss: 50459.9453 - val_mae: 50459.9453
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49607.4258 - mae: 49607.4258 - val_loss: 50445.2656 - val_mae: 50445.2656
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49592.5977 - mae: 49592.5977 - val_loss: 50429.3047 - val_mae: 50429.3047
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49576.3281 - mae: 49576.3281 - val_loss: 50421.9961 - val_mae: 50421.9961
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49434.3516 - mae: 49434.3516 - val_loss: 50420.3203 - val_mae: 50420.3203
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49894.7344 - mae: 49894.7344 - val_loss: 50408.4570 - val_mae: 50408.4570
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49607.2188 - mae: 49607.2188 - val_loss: 50395.3359 - val_mae: 50395.3359
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49071.6523 - mae: 49071.6523 - val_loss: 50390.1602 - val_mae: 50390.1602
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49597.7305 - mae: 49597.7305 - val_loss: 50388.6094 - val_mae: 50388.6094
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50313.1602 - mae: 50313.1602 - val_loss: 50385.1953 - val_mae: 50385.1953
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49208.2695 - mae: 49208.2695 - val_loss: 50377.7148 - val_mae: 50377.7148
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49049.4688 - mae: 49049.4688 - val_loss: 50372.9883 - val_mae: 50372.9883
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49904.6523 - mae: 49904.6523 - val_loss: 50368.0977 - val_mae: 50368.0977
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49621.7734 - mae: 49621.7734 - val_loss: 50362.2695 - val_mae: 50362.2695
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49210.1562 - mae: 49210.1562 - val_loss: 50359.1562 - val_mae: 50359.1562
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49745.2344 - mae: 49745.2344 - val_loss: 50363.7109 - val_mae: 50363.7109
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49460.5742 - mae: 49460.5742 - val_loss: 50354.9727 - val_mae: 50354.9727
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49484.6758 - mae: 49484.6758 - val_loss: 50356.2148 - val_mae: 50356.2148
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49613.4219 - mae: 49613.4219 - val_loss: 50362.2227 - val_mae: 50362.2227
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49924.6094 - mae: 49924.6094 - val_loss: 50355.4258 - val_mae: 50355.4258
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49812.7812 - mae: 49812.7812 - val_loss: 50354.8047 - val_mae: 50354.8047
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 48956.6094 - mae: 48956.6094 - val_loss: 50351.8711 - val_mae: 50351.8711
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49548.8906 - mae: 49548.8906 - val_loss: 50368.6445 - val_mae: 50368.6445
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49604.0898 - mae: 49604.0898 - val_loss: 50350.5195 - val_mae: 50350.5195
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49208.8945 - mae: 49208.8945 - val_loss: 50351.9648 - val_mae: 50351.9648
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49654.9570 - mae: 49654.9570 - val_loss: 50361.6602 - val_mae: 50361.6602
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49620.9102 - mae: 49620.9102 - val_loss: 50350.6094 - val_mae: 50350.6094
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49165.1719 - mae: 49165.1719 - val_loss: 50361.4648 - val_mae: 50361.4648
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49357.1445 - mae: 49357.1445 - val_loss: 50355.5742 - val_mae: 50355.5742
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50109.6758 - mae: 50109.6758 - val_loss: 50343.1055 - val_mae: 50343.1055
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49522.0430 - mae: 49522.0430 - val_loss: 50348.4883 - val_mae: 50348.4883
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49239.7656 - mae: 49239.7656 - val_loss: 50344.7773 - val_mae: 50344.7773
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49042.5156 - mae: 49042.5156 - val_loss: 50348.4688 - val_mae: 50348.4688
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49692.2188 - mae: 49692.2188 - val_loss: 50348.9102 - val_mae: 50348.9102
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49639.8633 - mae: 49639.8633 - val_loss: 50366.9844 - val_mae: 50366.9844
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49961.2461 - mae: 49961.2461 - val_loss: 50371.9922 - val_mae: 50371.9922
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49575.5195 - mae: 49575.5195 - val_loss: 50355.4648 - val_mae: 50355.4648
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49361.8516 - mae: 49361.8516 - val_loss: 50355.3125 - val_mae: 50355.3125
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 49101.4023 - mae: 49101.4023 - val_loss: 50356.8086 - val_mae: 50356.8086
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 49747.2109 - mae: 49747.2109 - val_loss: 50365.7188 - val_mae: 50365.7188

In [48]:
# load the tensorboard extension
%load_ext tensorboard

In [50]:
# launch tensorboard
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 41080), started 0:00:10 ago. (Use '!kill 41080' to kill it.)

In [51]:
# Evaluate the model
model.evaluate(X_test, y_test)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 51192.3438 - mae: 51192.3438

[50343.10546875, 50343.10546875]

In [52]:
# Saving the model
model.save('salary_prediction_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.